queue_rules:
  - name: duplicated default from Merge for developers
    queue_conditions:
      - base~=(mainline|rename-commands)
      - "#approved-reviews-by>=2"
      - approved-reviews-by=@aws/aws-ecs-devx
      - -approved-reviews-by~=author
      - status-success=build (compile-linux)
      - status-success=build (compile-windows)
      - status-success=build (compile-darwin)
      - status-success=test
      - status-success=staticcheck
      - status-success=license
      - -label~=(WIP|do-not-merge)
      - -title~=(WIP|wip)
      - -merged
      - -closed
      - author!=dependabot[bot]
    merge_conditions:
      - status-success=build (compile-linux)
      - status-success=build (compile-windows)
      - status-success=build (compile-darwin)
      - status-success=test
      - status-success=staticcheck
      - status-success=license
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash
  - name: duplicated default from Merge for bots
    queue_conditions:
      - base=mainline
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=build (compile-linux)
      - status-success=build (compile-windows)
      - status-success=build (compile-darwin)
      - status-success=test
      - status-success=staticcheck
      - status-success=license
      - author=dependabot[bot]
      - -title~=(WIP|wip)
      - -label~=(WIP|do-not-merge)
      - -merged
      - -closed
    merge_conditions:
      - status-success=build (compile-linux)
      - status-success=build (compile-windows)
      - status-success=build (compile-darwin)
      - status-success=test
      - status-success=staticcheck
      - status-success=license
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash
  - name: default
    conditions:
      - status-success=build (compile-linux)
      - status-success=build (compile-windows)
      - status-success=build (compile-darwin)
      - status-success=test
      - status-success=staticcheck
      - status-success=license

pull_request_rules:
  - name: Merge for bots
    conditions:
      - base=mainline
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=build (compile-linux)
      - status-success=build (compile-windows)
      - status-success=build (compile-darwin)
      - status-success=test
      - status-success=staticcheck
      - status-success=license
      - author=dependabot[bot]
      - -title~=(WIP|wip)
      - -label~=(WIP|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
  - name: Ask Japanese docs reviews
    conditions:
      - files~=\.ja.md$
      - -closed
    actions:
      request_reviews:
        users:
          - hkford
  - name: Merge for bots + Merge for developers
    conditions: []
    actions:
      queue:
